import { initReactI18next } from "react-i18next";
import i18n from "i18next";

const resources = {
  en: {
    translation: {
      home: "Home",
      dresses: 'Dresses',
      dressmakers: 'Dressmakers',
      blog: 'Blogs',
      deliveryAndPaymentOptions: 'Delivery and Payment Options',
      termsOfUse: 'Terms of Use (separate for dressmakers)',
      aboutUs: 'About Us',
      termAndConditions: 'Terms & Conditions',
      contactUs: 'Contact Us',
      subcribeNewsLetter: 'Subscribe Newsletter',
      enterEmail: "Enter your email",
      recommendedDress: "Recommended Dresses",
      viewAll: "View all",
      goto: "Go to",
      shop: "shop",
      s: "'s",
      tmt: 'TMT',
      add: "Add",
      mostPopularDresses: "Most Popular",
      more: "More",
      allCategories: "All categories",
      price: 'Price',
      rating: 'Rating',
      inStock: "In Stock",
      province: "Velayat",
      ashgabat: "Ashgabat",
      balkan: 'Balkan',
      ahal: "Ahal",
      mary: "Mary",
      lebap: "Lebap",
      dashoguz: "Dashoguz",
      _2_5days: "Delivery within 2-5 days to welayats",
      fabricName: "Fabric name",
      size: 'Size',
      color: "Color",
      comments: "Comments",
      similarDresses: "Similar goods",
      addToCard: "Add to card",
      numbers: "Quantity",
      total: "Total",
      order: "Order it",
      checkoutNow: "Checkout now",
      seller: "Seller",
      remindMe: "Remind me when it stock",
      remindMeWhenInStock: 'Remind me when it stock',
      remindMeText: 'You will be notified when item will be in stock again.',
      remindMePlaceholder: "Your email*",
      send: 'Send',
      myCart: 'My cart',
      remove: 'Remove',
      totalPrice: "Subtotal",
      or: 'or',
      continueShopping: 'Continue Shopping',
      yourOrder: "Your orders",
      discount: "Discount", //
      payment: "Payment", //
      cash: "Cash", //
      terminal: "Terminal", //
      myAccount: "My account",
      profile: "Profile",
      myAddresses: "My address",
      orders: "My orders",
      logout: "Logout",
      edit: "Edit",
      cancel: "Cancel",
      save: "Save",
      addressName: "Address name",
      name: "First name",
      phoneNumber: "Phone number",
      address: "Address",
      addNewAddress: "Add new address",
      doYouWantToLogout: "Do you really want to logout?",
      ok: "Ok",
      buyAgain: "Buy again", //
      user: "User", //
      whoWillUseWebsiteAs: "Do you want to be our customer or atelier/dressmaker?",
      customer: "Customer",
      dressmaker: "Ateliers and Dressmakers",
      hello: "Hello",
      welcomeDashboard: "Welcome back to dashboard",//
      users: 'Users', //
      comments: "Comments",
      onSale: "On sale",
      sizeChart: "Size chart",
      checkout: "Checkout",
      thereAre: "There are",
      productsInYourCart: "Products in your cart",
      billingDetails: "Billing Details", //
      firstName: "First name",
      lastName: "Last name",
      note: "Note",
      yourAddress: "Your address",
      products: "Products",
      quantity: "Quantity",
      subtotal: "Subtotal",
      addAddress: "Add address",
      editPhoto: "Edit photo",
      upload: "Upload",
      delete: "Delete",
      status: "Status",
      orderNumber: "Order number",
      date: "Date",
      leaveComment: "Leave a comment.",
      enterComment: "Enter your comment",
      giveRate: "Thank you for shopping with Lybas. Please rate your purchase and leave a comment.",
      clickToUpload: "Click to Upload",
      addComment: "Add comment",
      myFeedback: "My feedbacks",
      becomeMember: "Become a member", //Gerek dal
      signUp: "Sign up",
      signIn: "Sign in",
      password: "Password",
      confirmPassword: "Confirm password",
      rememberMe: "Remember me",
      forgotYourPassword: "Forgot your password?",
      confirm: "Confirm",
      enterTheCode: "Enter the code",
      verificationHelpWord: "Enter the verification code we sent to your phone number",
      bussinessName: "Atelier/brand name",
      verificationCode: "Verification code",
      waitToContact: "Wait to contact",
      waitToContactDefinition: "Thank you! We will contact you within 2-3 business days to verify your account.",
      deliveryAbroad: "Delivery Abroad",
      deliveryAbroadDefinition: "Please enter the URL link of the product you want to be shipped abroad and leave your contact details. We will get in touch with you regarding your inquiry.",
      URLlink: "URL link",
      doYouWantToDelete: "Do you really want to delete?",
      favorites: "Favorites",
      login: "Login",
      deliveryLocation: "Delivery location",
      notification: "Notifications",
      totalBalance: 'Total balance',
      thisMonth: "This month",
      overalRevenue: "Overal Revenue",
      monday: "Mo",
      tuesday: "Tu",
      wednesday: "We",
      thirsday: "Th",
      friday: "Fr",
      saturday: "Sa",
      sunday: "Su",
      next: "Next",
      prev: "Prev",
      reacentOrders: "Reacent Orders",
      addDress: "Add dress",
      searchHere: "Search here...",
      filter: "Filter",
      waiting: "Waiting",
      accepted: "Accepted",
      onTheWay: "Delivered",
      cancelled: "Cancelled",
      clientPhoneNumber: "Client, phone number",
      product: "Product",
      number: "Number",
      dateTime: "Date, time",
      status: "Status",
      result: "Result",
      fullName: "Full name",
      nameOfDressAndDressmaker: "Name of dress and Dressmaker",
      fabric: "Fabric",
      action: "Action",
      aboutTheDress: "About the dress",
      nameTm: "Name tm",
      nameEn: "Name en",
      nameRu: "Name ru",
      category: "Category",
      writeContentTm: "Write content tm",
      writeContentRu: "Write content ru",
      writeContentEn: "Write content en",
      uploadImage: "Upload image",
      nameLocation: "Name, Location",
      commentRating: "Comment, Rating",
      personalInformation: 'Personal Information',
      nameSimple: "Name",
      comment: "Comment",
      link: "Link",
      photos: "Photos",
      photo: "Photo",
      profileImage: "Profile image",
      emailPhoneNumber: "Email, Phone number",
      email: "Email",
      aboutOutStoke: "About out stoke",
      forgotPassword: "Forgot password?",
      heyWelcomeBack: "Hey Welcome Back",
      addDressmaker: "Add dressmaker",
      newDressmakerAdd: "New Dressmaker Add",
      filterName: "Filter name",
      addNewOne: "Add new one",
      image: "Image",
      bannerName: "Banner name",
      banner: "Banner",
      addBanner: 'Add Banner',
      aboutTheBanner: "About the banner",
      startAndEndDate: "Start and End Date",
      blogName: "Blog name",
      text: "Text",
      addBlog: "Add blog",
      addNotification: "Add notification",
      aboutTheNotification: "About the notification",
      textTm: "Text tm",
      textEn: "Text en",
      textRu: "Text ru",
      writeTheDetail: "Write in detail",
      fillTheGaps: "Fill free gaps!",
      type: "Type",
      new:"New",
      new:"New",
      newsletter:"Newsletter",
      outStock:"Out stock",
      newDressmaker:"New Dressmaker",
      information:"Informations",
      surname:"Surname",
      writePhoneNumber:"Write phone number",
      changePassword:"Change password",
      phoneNumberError:"Phone number is not correct",
      orderLaw: `<ul class='list-disc ml-5'>
                  <li>Eltip bermek hyzmaty Aşgabat şäheriniň çägi bilen bir hatarda Büzmeýine we Änew şäherine hem elýeterlidir;</li>
                  <li>Sargydyň iň pes çägi 50 manat bolmaly; 50-150 manat arasy eltip bermek hyzmatynyň tölegi 10 manat; sargydyňyz 150 manatdan geçse eltip bermek hyzmaty mugt;</li>
                  <li>Saýtdan sargyt edeniňizden soňra operator size jaň edip sargydy tassyklar (eger hemişelik müşderi bolsaňyz sargytlaryňyz islegiňize görä awtomatik usulda hem tassyklanýar);</li>
                  <li>Sargydy barlap alanyňyzdan soňra töleg amala aşyrylýar. Eltip berijiniň size gowşurýan töleg resminamasynda siziň tölemeli puluňyz bellenendir. Töleg nagt görnüşde milli manatda amala aşyrylýar. Kabul edip tölegini geçiren harydyňyz yzyna alynmaýar.</li>
                </ul>`
    },
  },

// //////////////////////////////////////////////////////////////////////////////////////////////////////////////////


  ru: {
    translation: {
      home: "Главная страница",
      dresses: 'Платья',
      dressmakers: 'Портнихи',
      blog: 'Блоги',
      deliveryAndPaymentOptions: 'Опции доставки и оплаты',
      termsOfUse: 'Условия использования (отдельно для портных)',
      aboutUs: 'О нас',
      termAndConditions: 'Условия и положения',
      contactUs: 'Связаться с нами',
      subcribeNewsLetter: 'Подписаться на рассылку',
      enterEmail: "Введите адрес электронной почты",
      recommendedDress: "Recommended Dresses ru",
      viewAll: "Посмотреть все",
      goto: "Перейти в магазин",
      shop: "shop ru",
      s: "'s",
      tmt: 'TMT',
      add: "Добавить",
      mostPopularDresses: "Самые популярные",
      more: "Подробнее",
      allCategories: "All categories",
      price: 'Цена',
      rating: 'Рейтинг',
      inStock: "В наличии",
      province: "Велаят",
      ashgabat: "Ашхабад",
      balkan: 'Балкан ',
      ahal: "Ахал",
      mary: "Мары",
      lebap: "Лебап",
      dashoguz: "Дашогуз",
      _2_5days: "Доставка в течение 2-5 дней в велаяты.",
      fabricName: "Fabric name",
      size: 'Размер',
      color: "Цвета",
      comments: "Отзывы",
      similarDresses: "Похожие товары",
      addToCard: "Добавить в корзину",
      numbers: "Количество",
      total: "Общая сумма",
      order: "Заказать",
      checkoutNow: "Оформить заказ",
      seller: "Продавец",
      remindMe: "Напомните мне, когда он появится в наличии",
      remindMeWhenInStock: 'Напомните мне, когда он появится в наличии',
      remindMeText: 'Вы будете уведомлены, когда товар снова появится в наличии.',
      remindMePlaceholder: "Ваш адрес электронной почты*",
      send: 'Отправить',
      myCart: 'Моя корзина',
      remove: 'Удалить',
      totalPrice: "Итого",
      or: 'или',
      continueShopping: 'продолжить покупку',
      yourOrder: "Ваши заказы",
      discount: "Discount",
      payment: "Payment",
      cash: "Cash",
      terminal: "Terminal",
      myAccount: "Мой аккаунт",
      profile: "Профиль",
      myAddresses: "Мой адрес",
      orders: "Мои заказы",
      logout: "Выйти",
      edit: "Редактировать",
      cancel: "Отмена",
      save: "Сохранить",
      addressName: "Мой адрес",
      name: "Имя",
      phoneNumber: "Номер телефона",
      address: "Ваш адрес",
      addNewAddress: "Добавить новый адрес",
      doYouWantToLogout: "Вы действительно хотите выйти из системы?",
      ok: "Ок",
      buyAgain: "Buy again",
      user: "User",
      whoWillUseWebsiteAs: "Хотите стать нашим клиентом или ателье/портнихой?",
      customer: "Клиентом",
      dressmaker: "Ателье и Портнихи",
      hello: "Привет", //
      welcomeDashboard: "Добро пожаловать обратно на панель управления",
      users: 'Users',
      comments: "Отзывы",
      onSale: "Скидки",
      sizeChart: "Таблица размеров",
      checkout: "Оформить заказ",
      thereAre: "В вашей корзине ",
      productsInYourCart: " товара",
      billingDetails: "Billing Details",
      firstName: "Имя",
      lastName: "Фамилия",
      note: "Примечания",
      yourAddress: "Ваш адрес",
      products: "Товари",
      quantity: "Количество",
      subtotal: "Итого",
      addAddress: "Добавить адрес",
      editPhoto: "Редактировать фотографию",
      upload: "Загрузить",
      delete: "Удалить",
      status: "Статус заказа",
      orderNumber: "Номер заказа",
      date: "Дата",
      leaveComment: "Oставьте отзыв.",
      enterComment: "Введите свой отзыв",
      giveRate: "Благодарим вас за покупку с Lybas. Пожалуйста, оцените покупку и оставьте отзыв.",
      clickToUpload: "Нажмите, чтобы загрузить",
      addComment: "Добавить отзыв",
      myFeedback: "Мои отзывы",
      becomeMember: "Become a member", //Gerekdal
      signUp: "Зарегистрироваться",
      signIn: "Войти",
      password: "Пароль",
      confirmPassword: "Подтвердите пароль",
      rememberMe: "Запомнить меня",
      forgotYourPassword: "Забыли пароль?",
      confirm: "Подтверждать",
      enterTheCode: "Введите код",
      verificationHelpWord: "Введите код подтверждения, который мы отправили на ваш номер телефона",
      bussinessName: "Название ателье/брэнда",
      verificationCode: "Код подтверждения",
      waitToContact: "Wait to contact", //
      waitToContactDefinition: "noСпасибо! Мы свяжемся с вами в течение 2-3 рабочих дней для проверки вашей учетной записи.",
      deliveryAbroad: "Доставка за границу",
      deliveryAbroadDefinition: "Пожалуйста, введите URL-ссылку на товар, который вы хотите отправить за границу, и оставьте свои контактные данные. Мы свяжемся с вами по поводу",
      URLlink: "URL-ссылка",
      doYouWantToDelete: "Do you really want to delete?", //
      favorites: "Favorites", //
      login: "Войти",
      deliveryLocation: "Адрес доставки",
      notification: "Уведомления",
      totalBalance: 'Общая сумма',
      thisMonth: "This month", //
      overalRevenue: "Overal Revenue", //
      monday: "Mo",
      tuesday: "Tu",
      wednesday: "We",
      thirsday: "Th",
      friday: "Fr",
      saturday: "Sa",
      sunday: "Su",
      next: "Next", //
      prev: "Prev", //
      reacentOrders: "Reacent Orders", //
      addDress: "Add dress", //
      searchHere: "Search here...", //
      filter: "фильтры",
      waiting: "Ожидается",
      accepted: "Принято",
      onTheWay: "Доставленный",
      cancelled: "Отменено",
      clientPhoneNumber: "Client, phone number",
      product: "Product",
      number: "Number",
      dateTime: "Date, time",
      status: "Status",
      result: "Result",
      fullName: "Full name",
      nameOfDressAndDressmaker: "Name of dress and Dressmaker",
      fabric: "Fabric",
      action: "Action",
      aboutTheDress: "About the dress",
      nameTm: "Имя tm",
      nameEn: "Имя en",
      nameRu: "Имя ru",
      category: "Category",
      writeContentTm: "Write content tm",
      writeContentRu: "Write content ru",
      writeContentEn: "Write content en",
      uploadImage: "Upload image",
      nameLocation: "Name, Location",
      commentRating: "Comment, Rating",
      personalInformation: 'Personal Information',
      nameSimple: "Имя",
      comment: "Comment",
      link: "Link",
      photos: "Photos",
      photo: "Photo",
      profileImage: "Profile image",
      emailPhoneNumber: "Email, Phone number",
      email: "Email",
      aboutOutStoke: "About out stoke",
      forgotPassword: "Forgot password?",
      heyWelcomeBack: "Hey Welcome Back",
      addDressmaker: "Add dressmaker",
      newDressmakerAdd: "New Dressmaker Add",
      filterName: "Filter name",
      addNewOne: "Add new one",
      image: "Image",
      bannerName: "Banner name",
      banner: "Баннер",
      addBanner: 'Add Banner',
      aboutTheBanner: "About the banner",
      startAndEndDate: "Start and End Date",
      blogName: "Blog name",
      text: "Text",
      addBlog: "Add blog",
      addNotification: "Add notification",
      aboutTheNotification: "About the notification",
      textTm: "Text tm",
      textEn: "Text en",
      textRu: "Text ru",
      writeTheDetail: "Write in detail",
      fillTheGaps: "Fill free gaps!",
      type: "Type",
      new:"New",
      newsletter:"Новостная рассылка",
      outStock:"Нет в наличии",
      newDressmaker:"Новая портниха",
      information:"Информация",
      surname:"Фамилия",
      writePhoneNumber:"Напишите номер телефона",
      changePassword:"Изменить пароль",
      phoneNumberError:"Номер телефона недействителен",
      orderLaw: `<ul class='list-disc ml-5'>
                  <li>Eltip bermek hyzmaty Aşgabat şäheriniň çägi bilen bir hatarda Büzmeýine we Änew şäherine hem elýeterlidir;</li>
                  <li>Sargydyň iň pes çägi 50 manat bolmaly; 50-150 manat arasy eltip bermek hyzmatynyň tölegi 10 manat; sargydyňyz 150 manatdan geçse eltip bermek hyzmaty mugt;</li>
                  <li>Saýtdan sargyt edeniňizden soňra operator size jaň edip sargydy tassyklar (eger hemişelik müşderi bolsaňyz sargytlaryňyz islegiňize görä awtomatik usulda hem tassyklanýar);</li>
                  <li>Sargydy barlap alanyňyzdan soňra töleg amala aşyrylýar. Eltip berijiniň size gowşurýan töleg resminamasynda siziň tölemeli puluňyz bellenendir. Töleg nagt görnüşde milli manatda amala aşyrylýar. Kabul edip tölegini geçiren harydyňyz yzyna alynmaýar.</li>
                </ul>`
    }
  },




// /////////////////////////////////////////////////////////////////////////////////////////////////////




  tm: {
    translation: {
      home: "Baş sahypa",
      dresses: 'Köýnekler',
      dressmakers: 'Satyjylar',
      blog: 'Blog',
      deliveryAndPaymentOptions: 'Eltip bermek we Töleg görnüşleri',
      termsOfUse: 'Ulanylyş düzgünleri (Satyjylar üçin aýratyn)',
      aboutUs: 'Biz barada',
      termAndConditions: 'Hukuklar & Şertler',
      contactUs: 'Biz bilen habarlaşmak',
      subcribeNewsLetter: 'Täzeliklere ýazylyň',
      enterEmail: "Email giriziň",
      recommendedDress: "Teklip edilýän köýnekler",
      viewAll: "Hemmesini görmek",
      goto: "Görmek",
      shop: "dükanyny",
      s: "-yň",
      tmt: "TMT",
      add: "Goşmak",
      mostPopularDresses: "Saýlananlar",
      more: "Giňişleýin",
      allCategories: "All categories", //
      price: 'Bahasy',
      rating: 'Reýting',
      inStock: "Elimizde bar",
      province: "Welaýat",
      ashgabat: "Aşgabat",
      balkan: 'Balkan',
      ahal: "Ahal",
      mary: "Mary",
      lebap: "Lebap",
      dashoguz: "Daşoguz",
      _2_5days: "Welaýatlara eltip bermek wagty 2-5 gün.",
      fabricName: "Fabric name", //
      size: 'Ölçegi',
      color: "Reňkler",
      comments: "Synlar",
      similarDresses: "Meňzeş harytlar",
      addToCard: "Sebete goşmak",
      numbers: "Mukdary",
      total: "Jemi",
      order: "Sargamak",
      checkoutNow: "Sargamak",
      seller: "Satyjy",
      remindMe: "Eliňize gelende maňa ýatladyň",
      remindMeWhenInStock: 'Eliňize gelende maňa ýatladyň',
      remindMeText: 'Haryt elimize gelende size habar bereris.',
      remindMePlaceholder: "E-poçta salgyňyz*",
      send: 'Ibermek',
      myCart: 'Sebedim',
      remove: 'Pozmak',
      totalPrice: "Jemi",
      or: 'ýada',
      continueShopping: 'söwda etmäge dowam etmek',
      yourOrder: "Sargytlaryňyz",
      discount: "Discount",
      payment: "Payment",
      cash: "Cash",
      terminal: "Terminal",
      myAccount: "Meniň akkaundym",
      profile: "Profil",
      myAddresses: "Öý salgym",
      orders: "Sargytlarym",
      logout: "Çykmak",
      edit: "Redaktirlemek",
      cancel: "Goýbolsun etmek",
      save: "Ýatda saklamak",
      addressName: "Öý salgym",
      name: "Adyňyz",
      phoneNumber: "Telefon belgiňiz",
      address: "Salgyňyz",
      addNewAddress: "Täze salgy goşmak",
      doYouWantToLogout: "Hakykatdan çykmak isleýärsiňizmi?",
      ok: "Ok",
      buyAgain: "Buy again", //
      user: "User", //
      whoWillUseWebsiteAs: "Müşderimiz hökmündemi ýa-da atelýe /tikinçi hökmünde agza bolmak isleýärsiňiz? Birini saýlaň?",
      customer: "Müşderi",
      dressmaker: "Atelýeler we Tikinçiler",
      hello: "Salam",
      welcomeDashboard: "Hoş geldiňiz",
      users: 'Users',
      comments: "Synlar",
      onSale: "Arzanladyşdakylar",
      sizeChart: "Ölçeg tablisasy",
      checkout: "Sargamak",
      thereAre: "Sebetiňizde ",
      productsInYourCart: " haryt bar",
      billingDetails: "Billing Details",
      firstName: "Adyňyz",
      lastName: "Familiýaňyz",
      note: "Bellik",
      yourAddress: "Salgyňyz",
      products: "Harytlar",
      quantity: "Mukdary",
      subtotal: "Jemi",
      addAddress: "Salgy goşmak",
      editPhoto: "Suraty redaktirlemek",
      upload: "Ýüklemek",
      delete: "Pozmak",
      status: "Sargyt ýagdaýy",
      orderNumber: "Sargyt belgisi",
      date: "Senesi",
      leaveComment: "Syn ýazmagyňyzy haýyş edýäris.",
      enterComment: "Synyňyzy ýazyň",
      giveRate: "Lybas bilen söwdaňyz üçin sag boluň. Satyn alan harydyňyza ýyldyz bilen baha berip syn ýazmagyňyzy haýyş edýäris.",
      clickToUpload: "Ýüklemek üçin basyň",
      addComment: "Syn goşmak",
      myFeedback: "Synlarym",
      becomeMember: "Become a member", //Gerekdal
      signUp: "Agza bolmak",
      signIn: "Girmek",
      password: "Parol",
      confirmPassword: "Paroly tassyklamak",
      rememberMe: "Meni ýatda saklamak",
      forgotYourPassword: "Parolyňyzy ýatdan çykardyňyzmy?",
      confirm: "Tassyklamak",
      enterTheCode: "Kody girizmek",
      verificationHelpWord: "Telefon belgiňize iberen tassyklama kody giriziň",
      bussinessName: "Atelýeňiziň / brendiňiziň ady",
      verificationCode: "Tassyklama kody",
      waitToContact: "Wait to contact", //
      waitToContactDefinition: "Sagboluň! Akkaundyňyzy tassyklamak üçin 2-3 iş gününiň dowamynda siz bilen habarlaşarys.",
      deliveryAbroad: "Daşary ýurda eltip bermek",
      deliveryAbroadDefinition: "Daşary ýurda ibermek isleýän harydyňyzyň URL ssylkasyny giriziň we aragatnaşyk maglumatlaryňyzy ýazyň. Siz bilen habarlaşarys.",
      URLlink: "URL ssylka",
      doYouWantToDelete: "Siz hakykatdanam pozmak isleýäňizmi?",
      favorites: "Halanlarym",
      login: "Girmek",
      deliveryLocation: "Eltip bermek salgysy",
      notification: "Täzelikler",
      totalBalance: 'Jemi',
      thisMonth: "Şu aý",
      overalRevenue: "Overal Revenue", //
      monday: "Mo",
      tuesday: "Tu",
      wednesday: "We",
      thirsday: "Th",
      friday: "Fr",
      saturday: "Sa",
      sunday: "Su",
      next: "Indiki",
      prev: "Öňki",
      reacentOrders: "Ýakyndaky zakazlar",
      addDress: "Köýnek goşmak",
      searchHere: "Gözlemek ...",
      filter: "Filter",
      waiting: "Garaşylýar",
      accepted: "Kabul edildi",
      onTheWay: "Gowşuruldy",
      cancelled: "Goýbolsun edildi",
      clientPhoneNumber: "Müşderi, telefon belgi",
      product: "Haryt",
      number: "Nomer",
      dateTime: "Sene, wagt",
      status: "Ýagdaýy",
      result: "Netije",
      fullName: "Doly ady",
      nameOfDressAndDressmaker: "Köýnegiň we Dikimçiň/Otelýaň ady",
      fabric: "Materialy",
      action: "Action",
      aboutTheDress: "Köýnek barada",
      nameTm: "Ady tm",
      nameEn: "Ady en",
      nameRu: "Ady ru",
      category: "Kategoriýa",
      writeContentTm: "Tekst ýazyň tm",
      writeContentRu: "Tekst ýazyň ru",
      writeContentEn: "Tekst ýazyň en",
      uploadImage: "Surat ýüklemek",
      nameLocation: "Ady, Ýerleşýän ýeri",
      commentRating: "Syn, rating",
      personalInformation: 'Şahsy Maglumat',
      nameSimple: "Ady",
      comment: "Syn",
      link: "Link",
      photos: "Suratlar",
      photo: "Surat",
      profileImage: "Profil surat",
      emailPhoneNumber: "Email, Telefon belgi",
      email: "Email",
      aboutOutStoke: "Elimizde ýoklar barada",
      forgotPassword: "Açar sözümi unutdum?",
      heyWelcomeBack: "Hoş geldiň",
      addDressmaker: "Dikimçi/Otelýa goşmak",
      newDressmakerAdd: "Täze Dikimçi/Otelýa goşmak",
      filterName: "Filter ady",
      addNewOne: "Täze birini goşmak",
      image: "Surat",
      bannerName: "Banner Ady",
      banner: "Banner",
      addBanner: 'Banner goşmak',
      aboutTheBanner: "Banner barada",
      startAndEndDate: "Başlaýan we gutarýan senesi",
      blogName: "Blog Ady",
      text: "Tekst",
      addBlog: "Blog goşmak",
      addNotification: "Täzelik goşmak",
      aboutTheNotification: "Täzelik barada",
      textTm: "Tekst tm",
      textEn: "Tekst en",
      textRu: "Tekst ru",
      writeTheDetail: "Maglumat ýaz",
      fillTheGaps: "Boşluklary dolduryň!",
      type: "Görnüşi",
      new:"Täze",
      newsletter:"Täzelikler",
      outStock:"Elimizde ýok",
      newDressmaker:"Täze tikinçi",
      information:"Maglumatlar",
      surname:"Familiýa",
      writePhoneNumber:"Telefon belgiňizi giriziň",
      changePassword:"Paroly üýtget",
      phoneNumberError:"Telefon belgi dogry däl",
      orderLaw: `<ul class='list-disc ml-5'>
                  <li>Eltip bermek hyzmaty Aşgabat şäheriniň çägi bilen bir hatarda Büzmeýine we Änew şäherine hem elýeterlidir;</li>
                  <li>Sargydyň iň pes çägi 50 manat bolmaly; 50-150 manat arasy eltip bermek hyzmatynyň tölegi 10 manat; sargydyňyz 150 manatdan geçse eltip bermek hyzmaty mugt;</li>
                  <li>Saýtdan sargyt edeniňizden soňra operator size jaň edip sargydy tassyklar (eger hemişelik müşderi bolsaňyz sargytlaryňyz islegiňize görä awtomatik usulda hem tassyklanýar);</li>
                  <li>Sargydy barlap alanyňyzdan soňra töleg amala aşyrylýar. Eltip berijiniň size gowşurýan töleg resminamasynda siziň tölemeli puluňyz bellenendir. Töleg nagt görnüşde milli manatda amala aşyrylýar. Kabul edip tölegini geçiren harydyňyz yzyna alynmaýar.</li>
                </ul>`
    }
  }
}

i18n
  .use(initReactI18next) // passes i18n down to react-i18next
  .init({
    resources,
    lng: localStorage.getItem('lang'), // language to use, more information here: https://www.i18next.com/overview/configuration-options#languages-namespaces-resources
    // you can use the i18n.changeLanguage function to change the language manually: https://www.i18next.com/overview/api#changelanguage
    // if you're using a language detector, do not define the lng option

    interpolation: {
      escapeValue: false // react already safes from xss
    }
  });

export default i18n;