import { initReactI18next } from "react-i18next";
import i18n from "i18next";

const resources = {
  en: {
    translation: {
      home: "Home",
      dresses: 'Dresses',
      dressmakers: 'Dressmakers',
      blog: 'Blog',
      deliveryAndPaymentOptions: 'Delivery and Payment Options',
      termsOfUse: 'Terms of Use (separate for dressmakers)',
      aboutUs: 'About Us',
      termAndConditions: 'Terms & Conditions',
      contactUs: 'Contact Us',
      subcribeNewsLetter: 'Subscribe Newsletter',
      enterEmail: "Enter your email",
      recommendedDress: "Recommended Dresses",
      viewAll: "View all",
      goto: "Go to",
      shop: "shop",
      s: "'s",
      tmt: 'TMT',
      add: "Add",
      mostPopularDresses: "Most Popular",
      more: "More",
      allCategories: "All categories",
      price: 'Price',
      rating: 'Rating',
      inStock: "In Stock",
      province: "Province",
      ashgabat: "Ashgabat",
      balkan: 'Balkan',
      ahal: "Ahal",
      mary: "Mary",
      lebap: "Lebap",
      dashoguz: "Dashoguz",
      _2_5days: "Beýleki welaýatlara 2-5 gün",
      fabricName: "Fabric name",
      size: 'Size',
      color: "Color",
      comments: "Comments",
      similarDresses: "Similar dresses",
      addToCard: "Add to card",
      numbers: "Numbers",
      total: "Total",
      order: "Order it",
      checkoutNow: "Checkout now",
      seller: "Seller",
      remindMe: "Remind me when in stock",
      remindMeWhenInStock: 'Remind me when in stock',
      remindMeText: 'You will be notified when the item arrives. Sorry for out of stock',
      remindMePlaceholder: "Your email or phone number*",
      send: 'Send',
      myCart: 'My cart',
      remove: 'Remove',
      totalPrice: "Total Price",
      or: 'or',
      continueShopping: 'Continue Shopping',
      yourOrder: "Your order",
      discount: "Discount",
      payment: "Payment",
      cash: "Cash",
      terminal: "Terminal",
      myAccount: "My account",
      profile: "Profile",
      myAddresses: "My addresses",
      orders: "Orders",
      logout: "Logout",
      edit: "Edit",
      cancel: "Cancel",
      save: "Save",
      addressName: "Address name",
      name: "Your name",
      phoneNumber: "Phone number",
      address: "Address",
      addNewAddress: "Add new address",
      doYouWantToLogout: "Do you really want to logout?",
      ok: "Ok",
      buyAgain: "Buy again",
      user: "User",
      whoWillUseWebsiteAs: "Who will you use the website as?",
      customer: "Customer",
      dressmaker: "Dressmaker",
      hello: "Hello",
      welcomeDashboard: "Welcome back to dashboard",
      users: 'Users',
      comments: "Comments",
      onSale: "On sale",
      sizeChart: "Size chart",
      checkout: "Checkout",
      thereAre: "There are",
      productsInYourCart: "Products in your cart",
      billingDetails: "Billing Details",
      firstName: "First name",
      lastName: "Last name",
      note: "Note",
      yourAddress: "Your address",
      products: "Products",
      quantity: "Quantity",
      subtotal: "Subtotal",
      addAddress: "Add address",
      editPhoto: "Edit photo",
      upload: "Upload",
      delete: "Delete",
      status: "Status",
      orderNumber: "Order number",
      date: "Date",
      leaveComment: "Leave a comment",
      enterComment: "Enter your comment",
      giveRate: "Satyn alan köýnegiňiz bahalandyryň we gysgaça teswir ýazyň",
      clickToUpload: "Click to Upload image",
      addComment: "Add comment",
      myFeedback: "My feedback",
      becomeMember: "Become a member",
      signUp: "Sign up",
      signIn: "Sign in",
      password: "Password",
      confirmPassword: "Confirm password",
      rememberMe: "Remember me",
      forgotYourPassword: "Forgot your password?",
      confirm: "Confirm",
      enterTheCode: "Enter the code",
      verificationHelpWord: "Enter the verification code received on the phone number",
      bussinessName: "Bussiness name",
      verificationCode: "Verification code",
      waitToContact: "Wait to contact",
      waitToContactDefinition: "notified dal, contacted. Within 30 minutes diyman within 1-2 business days",
      deliveryAbroad: "Delivery Abroad",
      deliveryAbroadDefinition: "Siz sargyt etjek köýnegiňiziň URL sylkasyny bellenen ýere goýuň we sargyt ediň",
      URLlink: "URL link",
      doYouWantToDelete: "Do you really want to delete?",
      favorites: "Favorites",
      login: "Login",
      deliveryLocation: "Delivery location",
      notification: "Notification",
      totalBalance: 'Total balance',
      thisMonth: "This month",
      overalRevenue: "Overal Revenue",
      monday: "Mo",
      tuesday: "Tu",
      wednesday: "We",
      thirsday: "Th",
      friday: "Fr",
      saturday: "Sa",
      sunday: "Su",
      next: "Next",
      prev: "Prev",
      reacentOrders: "Reacent Orders",
      addDress: "Add dress",
      searchHere: "Search here...",
      filter: "Filter",
      waiting:"Waiting",
      accepted:"Accepted",
      onTheWay:"On the way",
      cancelled:"Cancelled",
      clientPhoneNumber:"Client, phone number",
      product:"Product",
      number:"Number",
      dateTime:"Date, time",
      status:"Status",
      result:"Result",
      fullName:"Full name",
      nameOfDressAndDressmaker:"Name of dress and Dressmaker",
      fabric:"Fabric",
      action:"Action",
      aboutTheDress:"About the dress",
      nameTm:"Name tm",
      nameEn:"Name en",
      nameRu:"Name ru",
      category:"Category",
      writeContentTm:"Write content tm",
      writeContentRu:"Write content ru",
      writeContentEn:"Write content en",
      uploadImage:"Upload image",
      nameLocation:"Name, Location",
      commentRating:"Comment, Rating",
      personalInformation:'Personal Information',
      nameSimple:"Name",
      comment:"Comment",
      link:"Link",
      photos:"Photos",
      photo:"Photo",
      profileImage:"Profile image",
      emailPhoneNumber:"Email, Phone number",
      email:"Email",
      aboutOutStoke:"About out stoke",
      forgotPassword:"Forgot password?",
      heyWelcomeBack:"Hey Welcome Back",
      addDressmaker:"Add dressmaker",
      newDressmakerAdd:"New Dressmaker Add",
      filterName:"Filter name",
      addNewOne:"Add new one",
      image:"Image",
      bannerName:"Banner name",
      banner:"Banner",
      addBanner:'Add Banner',
      aboutTheBanner:"About the banner",
      startAndEndDate:"Start and End Date",
      blogName:"Blog name",
      text:"Text",
      addBlog:"Add blog",
      addNotification:"Add notification",
      aboutTheNotification:"About the notification",
      textTm:"Text tm",
      textEn:"Text en",
      textRu:"Text ru",
      writeTheDetail:"Write in detail",
      orderLaw: `<ul class='list-disc ml-5'>
                  <li>Eltip bermek hyzmaty Aşgabat şäheriniň çägi bilen bir hatarda Büzmeýine we Änew şäherine hem elýeterlidir;</li>
                  <li>Sargydyň iň pes çägi 50 manat bolmaly; 50-150 manat arasy eltip bermek hyzmatynyň tölegi 10 manat; sargydyňyz 150 manatdan geçse eltip bermek hyzmaty mugt;</li>
                  <li>Saýtdan sargyt edeniňizden soňra operator size jaň edip sargydy tassyklar (eger hemişelik müşderi bolsaňyz sargytlaryňyz islegiňize görä awtomatik usulda hem tassyklanýar);</li>
                  <li>Sargydy barlap alanyňyzdan soňra töleg amala aşyrylýar. Eltip berijiniň size gowşurýan töleg resminamasynda siziň tölemeli puluňyz bellenendir. Töleg nagt görnüşde milli manatda amala aşyrylýar. Kabul edip tölegini geçiren harydyňyz yzyna alynmaýar.</li>
                </ul>`
    },

  },
  ru: {
    translation: {
      home: "Домашняя",
      dresses: 'Платья',
      dressmakers: 'Портнихи',
      blog: 'Блог',
      deliveryAndPaymentOptions: 'Опции доставки и оплаты',
      termsOfUse: 'Условия использования (отдельно для портных)',
      aboutUs: 'О нас',
      termAndConditions: 'Условия и положения',
      contactUs: 'Связаться с нами',
      subcribeNewsLetter: 'Подписаться на рассылку',
      enterEmail: "Введите адрес электронной почты",
      recommendedDress: "Recommended Dresses ru",
      viewAll: "View all ru",
      goto: "Go to ru",
      shop: "shop ru",
      s: "'s ru",
      tmt: 'TMT',
    }
  },
  tm: {
    translation: {
      home: "Baş sahypa",
      dresses: 'Köýnekler',
      dressmakers: 'Satyjylar',
      blog: 'Blog',
      deliveryAndPaymentOptions: 'Eltip bermek we Töleg görnüşleri',
      termsOfUse: 'Ulanylyş düzgünleri (Satyjylar üçin aýratyn)',
      aboutUs: 'Biz barada',
      termAndConditions: 'Hukuklar & Şertler',
      contactUs: 'Biz bilen habarlaşmak',
      subcribeNewsLetter: 'Täzeliklere ýazylyň',
      enterEmail: "Email giriziň",
      recommendedDress: "Teklip edilýän köýnekler",
      viewAll: "Hemmesini görmek",
      goto: "Görmek",
      shop: "dükanyny",
      s: "-yň",
      tmt: "TMT",
    }
  }
}

i18n
  .use(initReactI18next) // passes i18n down to react-i18next
  .init({
    resources,
    lng: localStorage.getItem('lang'), // language to use, more information here: https://www.i18next.com/overview/configuration-options#languages-namespaces-resources
    // you can use the i18n.changeLanguage function to change the language manually: https://www.i18next.com/overview/api#changelanguage
    // if you're using a language detector, do not define the lng option

    interpolation: {
      escapeValue: false // react already safes from xss
    }
  });

export default i18n;